version: '3'

volumes:
  db-data:
    driver: local

  mongo-config:
    driver: local

services:
  pulseq-mongodb:
    image: mongo:latest
    container_name: pulseq-mongodb
    restart: always
    networks:
      - pulseq-net
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  pulseq:
    image: pulseq:0.0.1-pre-alpha.1
    container_name: pulseq
    restart: always
    networks:
      - pulseq-net
    ports:
      - "8080:8080"
    depends_on:
      - pulseq-mongodb

networks:
  pulseq-net:
    driver: bridge