version: '3'

volumes:
  db-data-postgres:
    driver: local

  db-data-postgres-config:
    driver: local

services:
  pulseq-postgres:
    image: postgres:9.6-bullseye
    container_name: pulseq-postgres
    environment:
      POSTGRES_DB: "pulseq-data"
      POSTGRES_USER: "pulseq-data"
      POSTGRES_PASSWORD: "pulseq-data"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - pulseq-net
    expose:
      - 5432
    volumes:
      - db-data-postgres-config:/var/lib/postgresql/dataConfig
      - db-data-postgres:/var/lib/postgresql/data

  pulseq:
    image: pulseq:0.3.0-alpha.0
    container_name: pulseq
    networks:
      - pulseq-net
    ports:
      - "8080:8080"
    depends_on:
      - pulseq-postgres
    environment:
      SPRING_DATA_MONGODB_HOST: pulseq-mongodb

networks:
  pulseq-net:
    driver: bridge
