spring:
  application:
    name: pulseq-client

pulseq:
  client:
    server-url: localhost:80
    server-secret: change-this
    device-name: some-device

    keyboard-listening-mode:
      count-down-latch:
        enabled: true
        count-trigger: 5

      timer:
        enabled: false
        delay: 1m