spring:
  application:
    name: pulseq-client

logging:
  level:
    org:
      springframework: debug

pulseq:
  client:
    server-url: https://pq.d1s.uno
    server-secret: sussy-baka
    device-name: arch

    keyboard-listening-mode:
      count-down-latch:
        enabled: true
        count-trigger: 5
