spring:
  application:
    name: pulseq-client

logging:
  level:
    org:
      springframework: debug

pulseq:
  client:
    server-url: http://localhost:8080
    server-secret: change-this
    device-name: arch

    keyboard-listening-mode:
      count-down-latch:
        enabled: true
        count-trigger: 5
