spring:

  profiles:
    active: "production"

  application:
    name: "pulseq"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pulseq-data
    username: pulseq-data
    password: pulseq-data

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-0.3.0-alpha.0.xml

  main:
    allow-circular-references: true # don't do it at home
    banner-mode:

server:
  servlet:
    context-path: /api

pulseq:
  version: "0.3.0-alpha.0"
  repository: "https://github.com/d1snin/pulseq"
  server-name: "my pulseq instance"

  security:
    secret: "change-this"

springdoc:
  api-docs:
    path: /docs-specifications

  swagger-ui:
    path: /docs