spring:
  application:
    name: pulseq

  data:
    mongodb:
      database: pulseq-data
      auto-index-creation: on
      host: localhost
      port: 27017

  config:
    import: file:../pulseq.yml

pulseq:
  version: "0.0.1-pre-alpha.1"
  repository: "https://github.com/d1snin/pulseq"
  security:
    secured-paths:
      - "T(BeatMappingConstants).BASE"
