pulseq:
  activity:
    activity-delimiter: "10s"
    long: "20s"
    warning: "50s"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: debug