spring:
  profiles:
    active: "production"

  application:
    name: "pulseq"

  data:
    mongodb:
      database: "pulseq-data"
      auto-index-creation: on
      host: "localhost"
      port: 27017

server:
  servlet:
    context-path: /api

pulseq:
  version: "0.2.1-alpha.0"
  repository: "https://github.com/d1snin/pulseq"
  server-name: "my pulseq instance"

  security:
    secret: "change-this"

springdoc:
  api-docs:
    path: /docs-specifications

  swagger-ui:
    path: /docs