spring:
  profiles:
    active: production

  application:
    name: pulseq

  data:
    mongodb:
      database: pulseq-data
      auto-index-creation: on
      host: localhost
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false

pulseq:
  version: 0.2.0-alpha.3
  repository: https://github.com/d1snin/pulseq

  security:
    secured-paths:
      - "/api/beat/"
      - "/api/device/new/"
    secret: change-this

  view:
    enabled: true