spring:
  application:
    name: pulseq

  data:
    mongodb:
      database: ${PULSEQ_MONGODB_DATABASE:pulseq-data}
      auto-index-creation: on
      host: ${PULSEQ_MONGODB_HOST:localhost}
      port: ${PULSEQ_MONGODB_PORT:27017}

pulseq:
  badge:
    color: ${PULSEQ_BADGE_COLOR:ff7878}

  version: ${PULSEQ_VERSION:0.0.2-alpha.3}
  repository: ${PULSEQ_REPOSITORY:"https://github.com/d1snin/pulseq"}

  inactivity:
    common: ${PULSEQ_COMMON_INACTIVITY:18000000}
    warning: ${PULSEQ_WARNING_INACTIVITY:86400000}

  notifications:
    discord:
      enabled: true
      webhooks: ${PULSEQ_DISCORD_WEBHOOKS:} # No default value, equivalent to empty string.

  security:
    secured-paths: ${PULSEQ_SECURED_PATHS:/api/beat/}
    secret: ${PULSEQ_SECRET:changeit}


server:
  port: ${PULSEQ_PORT:8080}

  error:
    whitelabel:
      enabled: false