spring:
  profiles:
    active: production

  application:
    name: pulseq

  data:
    mongodb:
      database: pulseq-data
      auto-index-creation: on
      host: ${PULSEQ_MONGODB_HOST:localhost}
      port: 27017

pulseq:
  version: 0.0.2-alpha.3
  repository: https://github.com/d1snin/pulseq

  security:
    secured-paths: /api/beat/
    secret: change-this

  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"