pulseq:
  activity:
    activity-delimiter: "10s"
    long: "20s"
    warning: "50s"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: debug